name = "CableLineModels"
uuid = "0c9747b7-a950-52d6-bf49-937d47305e1a"
authors = ["Stefan de Lange <langestefan@msn.com>"]
version = "0.1.0"

[workspace]
projects = ["test", "docs", "examples"]

[compat]
julia = "1.12"
